# Generated by Django 2.2.15 on 2023-08-25 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoundURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(unique=True)),
                ('viewed', models.BooleanField(default=False)),
                ('status_code', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('char_count', models.IntegerField()),
                ('word_count', models.IntegerField()),
                ('sentence_count', models.IntegerField()),
                ('raw_url', models.TextField()),
                ('url_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='search_engine.FoundURL')),
            ],
        ),
        migrations.CreateModel(
            name='ProcText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('char_count', models.IntegerField()),
                ('word_count', models.IntegerField()),
                ('sentence_count', models.IntegerField()),
                ('tokenized', models.BinaryField()),
                ('sentences', models.BinaryField()),
                ('raw_url', models.TextField()),
                ('raw_text_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='search_engine.RawText')),
            ],
        ),
    ]
